### ISSUE TITLE
Change name `scraper`

### ISSUE THREAD

**Issue by alirezaomidi** [alirezaomidi/iran-calendar-events#1]
Due to adding `setup.py`, we should choose an appropriate name for main script. Because after installing the script, it should be distinguishable from other packages appropriately.

**Comment by 733amir** [comment]
What do you think about "ircalendar"?

**Comment by alirezaomidi** [comment]
ircalendar-events ?!

**Comment by 733amir** [comment]
Limiting project to events?

**Comment by alirezaomidi** [comment]
Yes. This project is limited to events. There are some Python packages implementing Jalali calendar. E.g. Khayyam

**Comment by 733amir** [comment]
Ok. `ircalendar-events` is good.

**Comment by 733amir** [comment]
In python a module can't have `-` in its name.
It is better to use `ircalendarevents` or `ircalevents` or `ir_cal_events`.

**Comment by alirezaomidi** [comment]
`ircalevents` is good.

**Comment by 733amir** [comment]
DONE!
