### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by alirezaomidi** [alirezaomidi/iran-calendar-events#4]
Use [Travis CI](https://travis-ci.org/) to build and test the project.

**Comment by 733amir** [comment]
How [Travis CI](https://travis-ci.org/) is going to help us?

**Comment by alirezaomidi** [comment]
Read about it.
It runs builds the project for every commit, runs unit tests and gives a summary about it.

**Comment by 733amir** [comment]
I know what it do!
Give me an example of unit tests. Are we going to compare output of script? or ... ?!

**Comment by alirezaomidi** [comment]
There are several modules for creating unit tests.
We should use them to test every function and class.

**Comment by alirezaomidi** [comment]
Resolved in e833a42fab30a586be1ff209daf50db4788cec5e
